name: Caliper test
version: "2.0.0"
 
caliper:
 blockchain: fabric
 
channels:
 - channelName: autochannel
   contracts:
   - id: KBA-Automobile
 
organizations:
 - mspid: ManufacturerMSP
   identities:
     certificates:
     - name: 'User1'
       clientPrivateKey:
         path: '../KBA-Automobile/Automobile-network/organizations/peerOrganizations/manufacturer.auto.com/users/User1@manufacturer.auto.com/msp/keystore/fb3ed284ba796bc80ee09c37ece3e39e0d0bc529b5efa56bb2a5aeef348fa3de_sk'
       clientSignedCert:
         path: '../KBA-Automobile/Automobile-network/organizations/peerOrganizations/manufacturer.auto.com/users/User1@manufacturer.auto.com/msp/signcerts/cert.pem'
   peers:
      - endpoint: localhost:7051
        grpcOptions:
          ssl-target-name-override: peer0.manufacturer.auto.com
          grpc.keepalive_time_ms: 600000
        tlsCACerts:
          path: '../KBA-Automobile/Automobile-network/organizations/peerOrganizations/manufacturer.auto.com/peers/peer0.manufacturer.auto.com/msp/cacerts/localhost-7054-ca-manufacturer.pem'  